# Generated by Django 3.0.7 on 2020-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.IntegerField(verbose_name='柜号到港信息')),
                ('sku', models.CharField(max_length=64, verbose_name='商品编码')),
                ('productName', models.CharField(max_length=64, verbose_name='货物名称')),
                ('cabinetLength', models.IntegerField(verbose_name='柜子长度/cm')),
                ('cabinetWidth', models.IntegerField(verbose_name='柜子宽度/cm')),
                ('cabinetHeight', models.IntegerField(verbose_name='柜子高度/cm')),
                ('cabinetStyle', models.IntegerField(verbose_name='款式/cm')),
                ('cabinetCount', models.IntegerField(verbose_name='箱数')),
                ('onshowCount', models.IntegerField(verbose_name='仓库实际上架数量')),
                ('solidity', models.IntegerField(verbose_name='体积/cm^3')),
                ('solidityAll', models.IntegerField(verbose_name='总体积/cm^3')),
                ('grossWeight', models.IntegerField(verbose_name='毛重/kg')),
                ('grossWeightAll', models.IntegerField(verbose_name='总毛重/kg')),
                ('orderInfo', models.TextField(verbose_name='预约信息')),
            ],
        ),
    ]
