# Generated by Django 3.0.7 on 2020-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalplan',
            name='orderInfo',
            field=models.TextField(blank=True, null=True, verbose_name='预约信息'),
        ),
    ]
